import React from 'react';
import { Text } from 'react-native';
import {
    Building2,
    Store,
    Briefcase,
    Calculator,
    CircleDollarSign,
    Wallet,
    CreditCard,
    PieChart,
    BarChart3,
    TrendingUp,
    ShoppingBag,
    ShoppingCart,
    Truck,
    Wrench,
    Hammer,
    Utensils,
    Coffee,
    Pizza,
    Wine,
    Beer,
    Flower2,
    TreeDeciduous,
    Zap,
    Lightbulb,
    GraduationCap,
    School,
    BookOpen,
    Stethoscope,
    HeartPulse,
    Dumbbell,
    Trophy,
    Music,
    Camera,
    Video,
    Gamepad2,
    Rocket,
    // New imports for 200+ logos
    Plane,
    Car,
    Bike,
    Bus,
    Train,
    Ship,
    Anchor,
    Globe,
    Map,
    MapPin,
    Compass,
    Mountain,
    Palmtree,
    Sun,
    Moon,
    Cloud,
    CloudRain,
    Snowflake,
    Flame,
    Droplets,
    Wind,
    Leaf,
    Apple,
    Cherry,
    Banana,
    Carrot,
    Beef,
    Fish,
    Egg,
    Milk,
    IceCream,
    Cake,
    Cookie,
    Candy,
    Popcorn,
    Soup,
    Sandwich,
    Salad,
    ChefHat,
    UtensilsCrossed,
    Microwave,
    Refrigerator,
    CookingPot,
    Scissors,
    Paintbrush,
    Palette,
    PenTool,
    Pencil,
    Ruler,
    Eraser,
    Printer,
    Monitor,
    Laptop,
    Smartphone,
    Tablet,
    Watch,
    Headphones,
    Speaker,
    Radio,
    Tv,
    Wifi,
    Bluetooth,
    Signal,
    Battery,
    Power,
    Plug,
    Cable,
    Cpu,
    HardDrive,
    Database,
    Server,
    Code,
    Terminal,
    Bug,
    Shield,
    Lock,
    Key,
    Fingerprint,
    Eye,
    EyeOff,
    Bell,
    BellRing,
    Mail,
    Send,
    MessageSquare,
    MessageCircle,
    Phone,
    PhoneCall,
    AtSign,
    Hash,
    Search,
    Filter,
    Settings,
    Sliders,
    ToggleLeft,
    Layers,
    Layout,
    Grid,
    List,
    Table,
    Calendar,
    Clock,
    Timer,
    AlarmClock,
    Hourglass,
    History,
    Archive,
    Folder,
    FileText,
    File,
    Files,
    Clipboard,
    ClipboardList,
    ClipboardCheck,
    CheckSquare,
    XSquare,
    AlertTriangle,
    AlertCircle,
    Info,
    HelpCircle,
    Bookmark,
    Flag,
    Tag,
    Tags,
    Award,
    Medal,
    Crown,
    Star,
    Heart,
    ThumbsUp,
    ThumbsDown,
    Smile,
    Frown,
    Meh,
    Users,
    User,
    UserPlus,
    UserCheck,
    UserX,
    Baby,
    PersonStanding,
    Footprints,
    Hand,
    HandHeart,
    Brain,
    Bone,
    Pill,
    Syringe,
    Thermometer,
    Activity,
    Ambulance,
    Cross,
    Bandage,
    TestTube,
    Microscope,
    Dna,
    Atom,
    FlaskConical,
    Beaker,
    Scale,
    Gavel,
    Scroll,
    Receipt,
    Banknote,
    Coins,
    PiggyBank,
    Vault,
    Gem,
    Diamond,
    Gift,
    Package,
    Box,
    Boxes,
    Container,
    Factory,
    Building,
    Home,
    Hotel,
    Warehouse,
    Landmark,
    Church,
    Castle,
    Tent,
    Fence,
    Trees,
    ParkingCircle,
    Fuel,
    Construction,
    HardHat,
    Drill,
    Axe,
    Shovel,
    Tractor,
    Wheat,
    Sprout,
    Clover,
    TreePine,
    Bug as Insect,
    Bird,
    Cat,
    Dog,
    Rabbit,
    Squirrel,
    Turtle,
    Rat,
    Dog as Paw,
    Shell,
    Guitar,
    Piano,
    Drum,
    Mic,
    MicVocal,
    Ticket,
    Clapperboard,
    Film,
    Podcast,
    Newspaper,
    BookCopy,
    Library,
    Languages,
    Paintbrush2,
    Brush,
    Stamp,
    Frame,
    ImageIcon,
    ScanFace,
    CameraOff,
    Focus,
    SunMedium,
    Aperture,
    CircleDot,
    Crosshair,
    Target,
    Puzzle,
    Dice1,
    Dice5,
    Ghost,
    Swords,
    Bomb,
    Skull,
    Wand2,
    Sparkles,
    PartyPopper,
    Ribbon,
    Cake as BirthdayCake,
    GlassWater,
    Martini,
    CupSoda,
    Citrus,
    Grape,
    Nut
} from 'lucide-react-native';

export const BUSINESS_ICONS: Record<string, any> = {
    // Original icons
    'building': Building2,
    'store': Store,
    'briefcase': Briefcase,
    'calculator': Calculator,
    'dollar': CircleDollarSign,
    'wallet': Wallet,
    'card': CreditCard,
    'pie-chart': PieChart,
    'bar-chart': BarChart3,
    'trending': TrendingUp,
    'shopping-bag': ShoppingBag,
    'shopping-cart': ShoppingCart,
    'truck': Truck,
    'wrench': Wrench,
    'hammer': Hammer,
    'utensils': Utensils,
    'coffee': Coffee,
    'pizza': Pizza,
    'wine': Wine,
    'beer': Beer,
    'flower': Flower2,
    'tree': TreeDeciduous,
    'zap': Zap,
    'bulb': Lightbulb,
    'grad': GraduationCap,
    'school': School,
    'book': BookOpen,
    'stethoscope': Stethoscope,
    'heart': HeartPulse,
    'dumbbell': Dumbbell,
    'trophy': Trophy,
    'music': Music,
    'camera': Camera,
    'video': Video,
    'game': Gamepad2,
    'rocket': Rocket,
    // New icons
    'plane': Plane,
    'car': Car,
    'bike': Bike,
    'bus': Bus,
    'train': Train,
    'ship': Ship,
    'anchor': Anchor,
    'globe': Globe,
    'map': Map,
    'map-pin': MapPin,
    'compass': Compass,
    'mountain': Mountain,
    'palm': Palmtree,
    'sun': Sun,
    'moon': Moon,
    'cloud': Cloud,
    'rain': CloudRain,
    'snow': Snowflake,
    'flame': Flame,
    'water': Droplets,
    'wind': Wind,
    'leaf': Leaf,
    'apple': Apple,
    'cherry': Cherry,
    'banana': Banana,
    'carrot': Carrot,
    'beef': Beef,
    'fish': Fish,
    'egg': Egg,
    'milk': Milk,
    'icecream': IceCream,
    'cake': Cake,
    'cookie': Cookie,
    'candy': Candy,
    'popcorn': Popcorn,
    'soup': Soup,
    'sandwich': Sandwich,
    'salad': Salad,
    'chef': ChefHat,
    'cooking': UtensilsCrossed,
    'microwave': Microwave,
    'fridge': Refrigerator,
    'pot': CookingPot,
    'scissors': Scissors,
    'paintbrush': Paintbrush,
    'palette': Palette,
    'pen': PenTool,
    'pencil': Pencil,
    'ruler': Ruler,
    'eraser': Eraser,
    'printer': Printer,
    'monitor': Monitor,
    'laptop': Laptop,
    'phone': Smartphone,
    'tablet': Tablet,
    'watch': Watch,
    'headphones': Headphones,
    'speaker': Speaker,
    'radio': Radio,
    'tv': Tv,
    'wifi': Wifi,
    'bluetooth': Bluetooth,
    'signal': Signal,
    'battery': Battery,
    'power': Power,
    'plug': Plug,
    'cable': Cable,
    'cpu': Cpu,
    'harddrive': HardDrive,
    'database': Database,
    'server': Server,
    'code': Code,
    'terminal': Terminal,
    'bug': Bug,
    'shield': Shield,
    'lock': Lock,
    'key': Key,
    'fingerprint': Fingerprint,
    'eye': Eye,
    'eye-off': EyeOff,
    'bell': Bell,
    'bell-ring': BellRing,
    'mail': Mail,
    'send': Send,
    'message': MessageSquare,
    'chat': MessageCircle,
    'phone-call': PhoneCall,
    'at': AtSign,
    'hash': Hash,
    'search': Search,
    'filter': Filter,
    'settings': Settings,
    'sliders': Sliders,
    'toggle': ToggleLeft,
    'layers': Layers,
    'layout': Layout,
    'grid': Grid,
    'list': List,
    'table': Table,
    'calendar': Calendar,
    'clock': Clock,
    'timer': Timer,
    'alarm': AlarmClock,
    'hourglass': Hourglass,
    'history': History,
    'archive': Archive,
    'folder': Folder,
    'file-text': FileText,
    'file': File,
    'files': Files,
    'clipboard': Clipboard,
    'clipboard-list': ClipboardList,
    'clipboard-check': ClipboardCheck,
    'check-square': CheckSquare,
    'x-square': XSquare,
    'alert-triangle': AlertTriangle,
    'alert-circle': AlertCircle,
    'info': Info,
    'help': HelpCircle,
    'bookmark': Bookmark,
    'flag': Flag,
    'tag': Tag,
    'tags': Tags,
    'award': Award,
    'medal': Medal,
    'crown': Crown,
    'star': Star,
    'heart-icon': Heart,
    'thumbs-up': ThumbsUp,
    'thumbs-down': ThumbsDown,
    'smile': Smile,
    'frown': Frown,
    'meh': Meh,
    'users': Users,
    'user': User,
    'user-plus': UserPlus,
    'user-check': UserCheck,
    'user-x': UserX,
    'baby': Baby,
    'person': PersonStanding,
    'footprints': Footprints,
    'hand': Hand,
    'hand-heart': HandHeart,
    'brain': Brain,
    'bone': Bone,
    'pill': Pill,
    'syringe': Syringe,
    'thermometer': Thermometer,
    'activity': Activity,
    'ambulance': Ambulance,
    'cross': Cross,
    'bandage': Bandage,
    'test-tube': TestTube,
    'microscope': Microscope,
    'dna': Dna,
    'atom': Atom,
    'flask': FlaskConical,
    'beaker': Beaker,
    'scale': Scale,
    'gavel': Gavel,
    'scroll': Scroll,
    'receipt': Receipt,
    'banknote': Banknote,
    'coins': Coins,
    'piggy': PiggyBank,
    'vault': Vault,
    'gem': Gem,
    'diamond': Diamond,
    'gift': Gift,
    'package': Package,
    'box': Box,
    'boxes': Boxes,
    'container': Container,
    'factory': Factory,
    'building-alt': Building,
    'home': Home,
    'hotel': Hotel,
    'warehouse': Warehouse,
    'landmark': Landmark,
    'church': Church,
    'castle': Castle,
    'tent': Tent,
    'fence': Fence,
    'trees': Trees,
    'parking': ParkingCircle,
    'fuel': Fuel,
    'construction': Construction,
    'hardhat': HardHat,
    'drill': Drill,
    'axe': Axe,
    'shovel': Shovel,
    'tractor': Tractor,
    'wheat': Wheat,
    'sprout': Sprout,
    'clover': Clover,
    'cactus': TreePine,
    'insect': Insect,
    'bird': Bird,
    'cat': Cat,
    'dog': Dog,
    'rabbit': Rabbit,
    'squirrel': Squirrel,
    'turtle': Turtle,
    'rat': Rat,
    'paw': Paw,
    'shell': Shell,
    'guitar': Guitar,
    'piano': Piano,
    'drum': Drum,
    'mic': Mic,
    'mic-vocal': MicVocal,
    'ticket': Ticket,
    'clapperboard': Clapperboard,
    'film': Film,
    'podcast': Podcast,
    'newspaper': Newspaper,
    'book-copy': BookCopy,
    'library': Library,
    'languages': Languages,
    'brush': Brush,
    'stamp': Stamp,
    'frame': Frame,
    'image': ImageIcon,
    'scan': ScanFace,
    'camera-off': CameraOff,
    'focus': Focus,
    'sun-medium': SunMedium,
    'aperture': Aperture,
    'circle-dot': CircleDot,
    'crosshair': Crosshair,
    'target': Target,
    'puzzle': Puzzle,
    'dice': Dice5,
    'ghost': Ghost,
    'swords': Swords,
    'bomb': Bomb,
    'skull': Skull,
    'wand': Wand2,
    'sparkles': Sparkles,
    'party': PartyPopper,
    'martini': Martini,
    'soda': CupSoda,
    'citrus': Citrus,
    'grape': Grape,
    'nut': Nut
};

export interface LogoOption {
    id: string;
    icon: string;
    color: string;
    darkColor: string;
    label: string;
}

// Color palettes for variety
const COLORS = {
    blue: { color: '#10b981', darkColor: '#34d399' },
    indigo: { color: '#10b981', darkColor: '#34d399' },
    purple: { color: '#059669', darkColor: '#10b981' },
    emerald: { color: '#10b981', darkColor: '#34d399' },
    green: { color: '#059669', darkColor: '#10b981' },
    pink: { color: '#db2777', darkColor: '#ec4899' },
    rose: { color: '#e11d48', darkColor: '#f43f5e' },
    red: { color: '#dc2626', darkColor: '#ef4444' },
    orange: { color: '#ea580c', darkColor: '#f97316' },
    amber: { color: '#d97706', darkColor: '#f59e0b' },
    yellow: { color: '#ca8a04', darkColor: '#eab308' },
    lime: { color: '#65a30d', darkColor: '#84cc16' },
    teal: { color: '#0d9488', darkColor: '#14b8a6' },
    cyan: { color: '#0891b2', darkColor: '#06b6d4' },
    sky: { color: '#34d399', darkColor: '#10b981' },
    slate: { color: '#475569', darkColor: '#94a3b8' },
    gray: { color: '#64748b', darkColor: '#94a3b8' },
    brown: { color: '#78350f', darkColor: '#a8a29e' },
    wine: { color: '#9d174d', darkColor: '#d946ef' },
    forest: { color: '#14532d', darkColor: '#22c55e' },
};

export const LOGO_OPTIONS: LogoOption[] = [
    // Original 30 logos
    { id: '1', icon: 'store', color: '#10b981', darkColor: '#34d399', label: 'Retail' },
    { id: '2', icon: 'briefcase', color: '#10b981', darkColor: '#34d399', label: 'Corporate' },
    { id: '3', icon: 'shopping-bag', color: '#db2777', darkColor: '#ec4899', label: 'Fashion' },
    { id: '4', icon: 'utensils', color: '#ea580c', darkColor: '#f97316', label: 'Restaurant' },
    { id: '5', icon: 'coffee', color: '#7c2d12', darkColor: '#a8a29e', label: 'Cafe' },
    { id: '6', icon: 'wrench', color: '#4b5563', darkColor: '#9ca3af', label: 'Service' },
    { id: '7', icon: 'truck', color: '#059669', darkColor: '#10b981', label: 'Logistics' },
    { id: '8', icon: 'dollar', color: '#16a34a', darkColor: '#22c55e', label: 'Finance' },
    { id: '9', icon: 'building', color: '#0891b2', darkColor: '#06b6d4', label: 'Real Estate' },
    { id: '10', icon: 'trophy', color: '#ca8a04', darkColor: '#eab308', label: 'Sports' },
    { id: '11', icon: 'dumbbell', color: '#dc2626', darkColor: '#ef4444', label: 'Gym' },
    { id: '12', icon: 'stethoscope', color: '#be185d', darkColor: '#f43f5e', label: 'Medical' },
    { id: '13', icon: 'grad', color: '#7e22ce', darkColor: '#a855f7', label: 'Education' },
    { id: '14', icon: 'music', color: '#c026d3', darkColor: '#d946ef', label: 'Music' },
    { id: '15', icon: 'camera', color: '#0f172a', darkColor: '#94a3b8', label: 'Photography' },
    { id: '16', icon: 'game', color: '#9333ea', darkColor: '#c084fc', label: 'Gaming' },
    { id: '17', icon: 'rocket', color: '#e11d48', darkColor: '#f43f5e', label: 'Startup' },
    { id: '18', icon: 'tree', color: '#15803d', darkColor: '#22c55e', label: 'Nature' },
    { id: '19', icon: 'zap', color: '#fbbf24', darkColor: '#fcd34d', label: 'Electrical' },
    { id: '20', icon: 'bulb', color: '#d97706', darkColor: '#f59e0b', label: 'Ideas' },
    { id: '21', icon: 'pizza', color: '#b91c1c', darkColor: '#ef4444', label: 'Food' },
    { id: '22', icon: 'beer', color: '#d97706', darkColor: '#f59e0b', label: 'Bar' },
    { id: '23', icon: 'flower', color: '#be185d', darkColor: '#ec4899', label: 'Florist' },
    { id: '24', icon: 'book', color: '#059669', darkColor: '#10b981', label: 'Bookstore' },
    { id: '25', icon: 'calculator', color: '#374151', darkColor: '#6b7280', label: 'Accounting' },
    { id: '26', icon: 'pie-chart', color: '#0284c7', darkColor: '#38bdf8', label: 'Analytics' },
    { id: '27', icon: 'hammer', color: '#b45309', darkColor: '#f59e0b', label: 'Construction' },
    { id: '28', icon: 'shopping-cart', color: '#16a34a', darkColor: '#4ade80', label: 'Grocery' },
    { id: '29', icon: 'wine', color: '#9d174d', darkColor: '#d946ef', label: 'Winery' },
    { id: '30', icon: 'video', color: '#be123c', darkColor: '#f43f5e', label: 'Media' },
    // New 200+ logos
    { id: '31', icon: 'plane', ...COLORS.sky, label: 'Aviation' },
    { id: '32', icon: 'car', ...COLORS.slate, label: 'Auto Shop' },
    { id: '33', icon: 'bike', ...COLORS.green, label: 'Bicycle' },
    { id: '34', icon: 'bus', ...COLORS.yellow, label: 'Transit' },
    { id: '35', icon: 'train', ...COLORS.blue, label: 'Railway' },
    { id: '36', icon: 'ship', ...COLORS.cyan, label: 'Shipping' },
    { id: '37', icon: 'anchor', ...COLORS.teal, label: 'Marine' },
    { id: '38', icon: 'globe', ...COLORS.blue, label: 'Global' },
    { id: '39', icon: 'map', ...COLORS.emerald, label: 'Tourism' },
    { id: '40', icon: 'map-pin', ...COLORS.red, label: 'Location' },
    { id: '41', icon: 'compass', ...COLORS.amber, label: 'Adventure' },
    { id: '42', icon: 'mountain', ...COLORS.slate, label: 'Outdoor' },
    { id: '43', icon: 'palm', ...COLORS.green, label: 'Tropical' },
    { id: '44', icon: 'sun', ...COLORS.yellow, label: 'Solar' },
    { id: '45', icon: 'moon', ...COLORS.gray, label: 'Night' },
    { id: '46', icon: 'cloud', ...COLORS.sky, label: 'Cloud' },
    { id: '47', icon: 'rain', ...COLORS.blue, label: 'Weather' },
    { id: '48', icon: 'snow', ...COLORS.cyan, label: 'Winter' },
    { id: '49', icon: 'flame', ...COLORS.orange, label: 'Fire' },
    { id: '50', icon: 'water', ...COLORS.blue, label: 'Water' },
    { id: '51', icon: 'wind', ...COLORS.teal, label: 'Air' },
    { id: '52', icon: 'leaf', ...COLORS.green, label: 'Eco' },
    { id: '53', icon: 'apple', ...COLORS.red, label: 'Fruits' },
    { id: '54', icon: 'cherry', ...COLORS.rose, label: 'Berries' },
    { id: '55', icon: 'banana', ...COLORS.yellow, label: 'Produce' },
    { id: '56', icon: 'carrot', ...COLORS.orange, label: 'Veggies' },
    { id: '57', icon: 'beef', ...COLORS.brown, label: 'Butcher' },
    { id: '58', icon: 'fish', ...COLORS.cyan, label: 'Seafood' },
    { id: '59', icon: 'egg', ...COLORS.amber, label: 'Poultry' },
    { id: '60', icon: 'milk', ...COLORS.slate, label: 'Dairy' },
    { id: '61', icon: 'icecream', ...COLORS.pink, label: 'Ice Cream' },
    { id: '62', icon: 'cake', ...COLORS.rose, label: 'Bakery' },
    { id: '63', icon: 'cookie', ...COLORS.brown, label: 'Cookies' },
    { id: '64', icon: 'candy', ...COLORS.pink, label: 'Candy' },
    { id: '65', icon: 'popcorn', ...COLORS.yellow, label: 'Cinema' },
    { id: '66', icon: 'soup', ...COLORS.orange, label: 'Soup' },
    { id: '67', icon: 'sandwich', ...COLORS.amber, label: 'Deli' },
    { id: '68', icon: 'salad', ...COLORS.green, label: 'Healthy' },
    { id: '69', icon: 'chef', ...COLORS.slate, label: 'Chef' },
    { id: '70', icon: 'cooking', ...COLORS.orange, label: 'Cooking' },
    { id: '71', icon: 'microwave', ...COLORS.gray, label: 'Appliance' },
    { id: '72', icon: 'fridge', ...COLORS.cyan, label: 'Kitchen' },
    { id: '73', icon: 'pot', ...COLORS.slate, label: 'Catering' },
    { id: '74', icon: 'scissors', ...COLORS.purple, label: 'Salon' },
    { id: '75', icon: 'paintbrush', ...COLORS.pink, label: 'Art' },
    { id: '76', icon: 'palette', ...COLORS.purple, label: 'Design' },
    { id: '77', icon: 'pen', ...COLORS.blue, label: 'Writing' },
    { id: '78', icon: 'pencil', ...COLORS.amber, label: 'Drawing' },
    { id: '79', icon: 'ruler', ...COLORS.slate, label: 'Measure' },
    { id: '80', icon: 'eraser', ...COLORS.pink, label: 'Stationery' },
    { id: '81', icon: 'printer', ...COLORS.gray, label: 'Printing' },
    { id: '82', icon: 'monitor', ...COLORS.slate, label: 'Desktop' },
    { id: '83', icon: 'laptop', ...COLORS.indigo, label: 'Tech' },
    { id: '84', icon: 'phone', ...COLORS.blue, label: 'Mobile' },
    { id: '85', icon: 'tablet', ...COLORS.purple, label: 'Tablet' },
    { id: '86', icon: 'watch', ...COLORS.slate, label: 'Watch' },
    { id: '87', icon: 'headphones', ...COLORS.purple, label: 'Audio' },
    { id: '88', icon: 'speaker', ...COLORS.slate, label: 'Sound' },
    { id: '89', icon: 'radio', ...COLORS.amber, label: 'Radio' },
    { id: '90', icon: 'tv', ...COLORS.blue, label: 'Television' },
    { id: '91', icon: 'wifi', ...COLORS.cyan, label: 'Internet' },
    { id: '92', icon: 'bluetooth', ...COLORS.blue, label: 'Connect' },
    { id: '93', icon: 'signal', ...COLORS.green, label: 'Network' },
    { id: '94', icon: 'battery', ...COLORS.green, label: 'Power' },
    { id: '95', icon: 'plug', ...COLORS.yellow, label: 'Electric' },
    { id: '96', icon: 'cable', ...COLORS.slate, label: 'Cable' },
    { id: '97', icon: 'cpu', ...COLORS.indigo, label: 'Hardware' },
    { id: '98', icon: 'harddrive', ...COLORS.slate, label: 'Storage' },
    { id: '99', icon: 'database', ...COLORS.blue, label: 'Data' },
    { id: '100', icon: 'server', ...COLORS.slate, label: 'Server' },
    { id: '101', icon: 'code', ...COLORS.indigo, label: 'Dev' },
    { id: '102', icon: 'terminal', ...COLORS.green, label: 'Terminal' },
    { id: '103', icon: 'bug', ...COLORS.red, label: 'QA' },
    { id: '104', icon: 'shield', ...COLORS.blue, label: 'Security' },
    { id: '105', icon: 'lock', ...COLORS.slate, label: 'Privacy' },
    { id: '106', icon: 'key', ...COLORS.yellow, label: 'Access' },
    { id: '107', icon: 'fingerprint', ...COLORS.purple, label: 'Biometric' },
    { id: '108', icon: 'eye', ...COLORS.cyan, label: 'Vision' },
    { id: '109', icon: 'bell', ...COLORS.yellow, label: 'Notify' },
    { id: '110', icon: 'mail', ...COLORS.blue, label: 'Email' },
    { id: '111', icon: 'send', ...COLORS.indigo, label: 'Courier' },
    { id: '112', icon: 'message', ...COLORS.green, label: 'Chat' },
    { id: '113', icon: 'chat', ...COLORS.blue, label: 'Message' },
    { id: '114', icon: 'phone-call', ...COLORS.green, label: 'Call Center' },
    { id: '115', icon: 'at', ...COLORS.indigo, label: 'Social' },
    { id: '116', icon: 'hash', ...COLORS.pink, label: 'Trending' },
    { id: '117', icon: 'search', ...COLORS.slate, label: 'Search' },
    { id: '118', icon: 'filter', ...COLORS.purple, label: 'Filter' },
    { id: '119', icon: 'settings', ...COLORS.gray, label: 'Settings' },
    { id: '120', icon: 'sliders', ...COLORS.slate, label: 'Control' },
    { id: '121', icon: 'layers', ...COLORS.indigo, label: 'Layers' },
    { id: '122', icon: 'layout', ...COLORS.blue, label: 'Layout' },
    { id: '123', icon: 'grid', ...COLORS.slate, label: 'Grid' },
    { id: '124', icon: 'list', ...COLORS.gray, label: 'List' },
    { id: '125', icon: 'table', ...COLORS.emerald, label: 'Table' },
    { id: '126', icon: 'calendar', ...COLORS.red, label: 'Events' },
    { id: '127', icon: 'clock', ...COLORS.slate, label: 'Time' },
    { id: '128', icon: 'timer', ...COLORS.orange, label: 'Timer' },
    { id: '129', icon: 'alarm', ...COLORS.red, label: 'Alarm' },
    { id: '130', icon: 'hourglass', ...COLORS.amber, label: 'Wait' },
    { id: '131', icon: 'history', ...COLORS.slate, label: 'History' },
    { id: '132', icon: 'archive', ...COLORS.brown, label: 'Archive' },
    { id: '133', icon: 'folder', ...COLORS.yellow, label: 'Files' },
    { id: '134', icon: 'file-text', ...COLORS.blue, label: 'Docs' },
    { id: '135', icon: 'clipboard', ...COLORS.slate, label: 'Clipboard' },
    { id: '136', icon: 'clipboard-list', ...COLORS.indigo, label: 'Tasks' },
    { id: '137', icon: 'check-square', ...COLORS.green, label: 'Complete' },
    { id: '138', icon: 'alert-triangle', ...COLORS.yellow, label: 'Warning' },
    { id: '139', icon: 'info', ...COLORS.blue, label: 'Info' },
    { id: '140', icon: 'help', ...COLORS.purple, label: 'Help' },
    { id: '141', icon: 'bookmark', ...COLORS.red, label: 'Bookmark' },
    { id: '142', icon: 'flag', ...COLORS.red, label: 'Flag' },
    { id: '143', icon: 'tag', ...COLORS.green, label: 'Tag' },
    { id: '144', icon: 'tags', ...COLORS.purple, label: 'Tags' },
    { id: '145', icon: 'award', ...COLORS.yellow, label: 'Award' },
    { id: '146', icon: 'medal', ...COLORS.amber, label: 'Medal' },
    { id: '147', icon: 'crown', ...COLORS.yellow, label: 'Royal' },
    { id: '148', icon: 'star', ...COLORS.yellow, label: 'Star' },
    { id: '149', icon: 'heart-icon', ...COLORS.red, label: 'Love' },
    { id: '150', icon: 'thumbs-up', ...COLORS.blue, label: 'Like' },
    { id: '151', icon: 'smile', ...COLORS.yellow, label: 'Happy' },
    { id: '152', icon: 'users', ...COLORS.blue, label: 'Team' },
    { id: '153', icon: 'user', ...COLORS.slate, label: 'User' },
    { id: '154', icon: 'user-plus', ...COLORS.green, label: 'Join' },
    { id: '155', icon: 'baby', ...COLORS.pink, label: 'Baby' },
    { id: '156', icon: 'person', ...COLORS.slate, label: 'Person' },
    { id: '157', icon: 'footprints', ...COLORS.brown, label: 'Walk' },
    { id: '158', icon: 'hand', ...COLORS.amber, label: 'Hand' },
    { id: '159', icon: 'hand-heart', ...COLORS.red, label: 'Charity' },
    { id: '160', icon: 'brain', ...COLORS.pink, label: 'Brain' },
    { id: '161', icon: 'bone', ...COLORS.slate, label: 'Ortho' },
    { id: '162', icon: 'pill', ...COLORS.red, label: 'Pharmacy' },
    { id: '163', icon: 'syringe', ...COLORS.cyan, label: 'Clinic' },
    { id: '164', icon: 'thermometer', ...COLORS.red, label: 'Fever' },
    { id: '165', icon: 'activity', ...COLORS.green, label: 'Vital' },
    { id: '166', icon: 'ambulance', ...COLORS.red, label: 'Emergency' },
    { id: '167', icon: 'cross', ...COLORS.red, label: 'Health' },
    { id: '168', icon: 'bandage', ...COLORS.pink, label: 'First Aid' },
    { id: '169', icon: 'test-tube', ...COLORS.purple, label: 'Lab' },
    { id: '170', icon: 'microscope', ...COLORS.indigo, label: 'Research' },
    { id: '171', icon: 'dna', ...COLORS.purple, label: 'Genetics' },
    { id: '172', icon: 'atom', ...COLORS.blue, label: 'Science' },
    { id: '173', icon: 'flask', ...COLORS.green, label: 'Chemistry' },
    { id: '174', icon: 'beaker', ...COLORS.cyan, label: 'Beaker' },
    { id: '175', icon: 'scale', ...COLORS.slate, label: 'Legal' },
    { id: '176', icon: 'gavel', ...COLORS.brown, label: 'Court' },
    { id: '177', icon: 'scroll', ...COLORS.amber, label: 'Contract' },
    { id: '178', icon: 'receipt', ...COLORS.slate, label: 'Invoice' },
    { id: '179', icon: 'banknote', ...COLORS.green, label: 'Cash' },
    { id: '180', icon: 'coins', ...COLORS.yellow, label: 'Coins' },
    { id: '181', icon: 'piggy', ...COLORS.pink, label: 'Savings' },
    { id: '182', icon: 'vault', ...COLORS.slate, label: 'Vault' },
    { id: '183', icon: 'gem', ...COLORS.purple, label: 'Jewelry' },
    { id: '184', icon: 'diamond', ...COLORS.cyan, label: 'Diamond' },
    { id: '185', icon: 'gift', ...COLORS.red, label: 'Gift Shop' },
    { id: '186', icon: 'package', ...COLORS.brown, label: 'Packages' },
    { id: '187', icon: 'box', ...COLORS.amber, label: 'Box' },
    { id: '188', icon: 'boxes', ...COLORS.slate, label: 'Boxes' },
    { id: '189', icon: 'container', ...COLORS.blue, label: 'Container' },
    { id: '190', icon: 'factory', ...COLORS.slate, label: 'Factory' },
    { id: '191', icon: 'building-alt', ...COLORS.blue, label: 'Building' },
    { id: '192', icon: 'home', ...COLORS.green, label: 'Home' },
    { id: '193', icon: 'hotel', ...COLORS.purple, label: 'Hotel' },
    { id: '194', icon: 'warehouse', ...COLORS.slate, label: 'Warehouse' },
    { id: '195', icon: 'landmark', ...COLORS.amber, label: 'Government' },
    { id: '196', icon: 'church', ...COLORS.purple, label: 'Church' },
    { id: '197', icon: 'castle', ...COLORS.slate, label: 'Castle' },
    { id: '198', icon: 'tent', ...COLORS.green, label: 'Camping' },
    { id: '199', icon: 'fence', ...COLORS.brown, label: 'Fencing' },
    { id: '200', icon: 'trees', ...COLORS.green, label: 'Forestry' },
    { id: '201', icon: 'parking', ...COLORS.blue, label: 'Parking' },
    { id: '202', icon: 'fuel', ...COLORS.yellow, label: 'Gas' },
    { id: '203', icon: 'construction', ...COLORS.orange, label: 'Build' },
    { id: '204', icon: 'hardhat', ...COLORS.yellow, label: 'Safety' },
    { id: '205', icon: 'drill', ...COLORS.slate, label: 'Tools' },
    { id: '206', icon: 'axe', ...COLORS.brown, label: 'Lumber' },
    { id: '207', icon: 'shovel', ...COLORS.slate, label: 'Dig' },
    { id: '208', icon: 'tractor', ...COLORS.green, label: 'Farm' },
    { id: '209', icon: 'wheat', ...COLORS.amber, label: 'Grain' },
    { id: '210', icon: 'sprout', ...COLORS.green, label: 'Garden' },
    { id: '211', icon: 'clover', ...COLORS.green, label: 'Clover' },
    { id: '212', icon: 'cactus', ...COLORS.green, label: 'Desert' },
    { id: '213', icon: 'insect', ...COLORS.green, label: 'Pest' },
    { id: '214', icon: 'bird', ...COLORS.blue, label: 'Bird' },
    { id: '215', icon: 'cat', ...COLORS.slate, label: 'Cat' },
    { id: '216', icon: 'dog', ...COLORS.brown, label: 'Dog' },
    { id: '217', icon: 'rabbit', ...COLORS.pink, label: 'Rabbit' },
    { id: '218', icon: 'squirrel', ...COLORS.amber, label: 'Squirrel' },
    { id: '219', icon: 'turtle', ...COLORS.green, label: 'Turtle' },
    { id: '220', icon: 'paw', ...COLORS.brown, label: 'Pet Shop' },
    { id: '221', icon: 'shell', ...COLORS.cyan, label: 'Shell' },
    { id: '222', icon: 'guitar', ...COLORS.amber, label: 'Guitar' },
    { id: '223', icon: 'piano', ...COLORS.slate, label: 'Piano' },
    { id: '224', icon: 'drum', ...COLORS.orange, label: 'Drums' },
    { id: '225', icon: 'mic', ...COLORS.slate, label: 'Karaoke' },
    { id: '226', icon: 'mic-vocal', ...COLORS.purple, label: 'Singer' },
    { id: '227', icon: 'ticket', ...COLORS.red, label: 'Tickets' },
    { id: '228', icon: 'clapperboard', ...COLORS.slate, label: 'Film' },
    { id: '229', icon: 'film', ...COLORS.purple, label: 'Movie' },
    { id: '230', icon: 'podcast', ...COLORS.purple, label: 'Podcast' },
    { id: '231', icon: 'newspaper', ...COLORS.slate, label: 'News' },
    { id: '232', icon: 'book-copy', ...COLORS.blue, label: 'Publisher' },
    { id: '233', icon: 'library', ...COLORS.brown, label: 'Library' },
    { id: '234', icon: 'languages', ...COLORS.indigo, label: 'Language' },
    { id: '235', icon: 'brush', ...COLORS.pink, label: 'Brush' },
    { id: '236', icon: 'stamp', ...COLORS.red, label: 'Stamp' },
    { id: '237', icon: 'frame', ...COLORS.brown, label: 'Frame' },
    { id: '238', icon: 'image', ...COLORS.purple, label: 'Image' },
    { id: '239', icon: 'scan', ...COLORS.blue, label: 'Scan' },
    { id: '240', icon: 'focus', ...COLORS.slate, label: 'Focus' },
    { id: '241', icon: 'aperture', ...COLORS.purple, label: 'Lens' },
    { id: '242', icon: 'crosshair', ...COLORS.red, label: 'Target' },
    { id: '243', icon: 'target', ...COLORS.red, label: 'Goal' },
    { id: '244', icon: 'puzzle', ...COLORS.purple, label: 'Puzzle' },
    { id: '245', icon: 'dice', ...COLORS.red, label: 'Casino' },
    { id: '246', icon: 'ghost', ...COLORS.slate, label: 'Ghost' },
    { id: '247', icon: 'swords', ...COLORS.slate, label: 'Combat' },
    { id: '248', icon: 'wand', ...COLORS.purple, label: 'Magic' },
    { id: '249', icon: 'sparkles', ...COLORS.yellow, label: 'Sparkle' },
    { id: '250', icon: 'party', ...COLORS.pink, label: 'Party' },
    { id: '251', icon: 'martini', ...COLORS.purple, label: 'Cocktail' },
    { id: '252', icon: 'soda', ...COLORS.red, label: 'Soda' },
    { id: '253', icon: 'citrus', ...COLORS.yellow, label: 'Citrus' },
    { id: '254', icon: 'grape', ...COLORS.purple, label: 'Grape' },
    { id: '255', icon: 'nut', ...COLORS.brown, label: 'Nuts' },
];

// Emoji Support
const EmojiWrapper = (emoji: string) => (props: any) =>
    React.createElement(Text, {
        style: {
            fontSize: props.size || 24,
            textAlign: 'center',
            color: props.color
        }
    }, emoji);

const EMOJI_DATA = [
  {
    label: "🙂",
    data: [
      "😀","😃","😄","😁","😆","😅","😂","🤣","🥲","☺️","😊","😇","🙂","🙃","😉","😌",
      "😍","🥰","😘","😗","😙","😚","😋","😛","😝","😜","🤪","🤨","🧐","🤓","😎",
      "🥸","🤩","🥳","😏","😒","😞","😔","😟","😕","🙁","☹️","😣","😖","😫","😩",
      "🥺","😢","😭","😤","😠","😡","🤬","🤯","😳","🥵","🥶","😱","😨","😰","😥",
      "😓","🤗","🤔","🤭","🤫","🤥","😶","😐","😑","😬","🙄","😯","😦","😧","😮",
      "😲","🥱","😴","🤤","😪","😵","🤐","🥴","🤢","🤮","🤧","😷","🤒","🤕","🤑",
      "🤠","😈","👿","👹","👺","🤡","💩","👻","💀","☠️","👽","👾","🤖","🎃",
      "😺","😸","😻","😼","😽","🙀","😿","😾"
    ]
  },

  {
    label: "🐶",
    data: [
      "🐶","🐱","🐭","🐹","🐰","🦊","🐻","🐼","🐨","🐯","🦁","🐮","🐷","🐽","🐸","🐵",
      "🙈","🙉","🙊","🐒","🐔","🐧","🐦","🐥","🐤","🐣","🦆","🦅","🦉","🦇","🐺",
      "🐗","🐴","🦄","🐝","🐛","🦋","🐌","🐞","🐜","🦟","🕷","🕸","🦂","🐢","蛇",
      "蜥","🦖","🦕","🐙","🦑","🦐","🦞","🦀","🐡","🐠","🐟","🐬","🐳","🐋","🦈",
      "🐊","🐅","豹","🦓","🦍","🦧","🐘","🦛","🦏","🐪","🐫","🦒","🦘","🦬","🐃",
      "🐂","🐄","🐎","🐖","🐏","🐑","🦙","🐐","🦌","🐕","🐩","🐈","🐓","🦃","🦚",
      "🦜","🦢","🦩","🕊","🐇","🦝","🦨","🦡","🦦","🦥","🐁","🐀","🐿","🦔","🐾"
    ]
  },

  {
    label: "🍔",
    data: [
      "🍏","🍎","🍐","🍊","🍋","🍌","🍉","🍇","🍓","🫐","🍈","🍒","🍑","🥭","🍍",
      "🥥","🥝","🍅","🍆","🥑","🥦","🥬","🥒","🌶","🫑","🌽","🥕","🫒","🧄","🧅",
      "🥔","🍠","🥐","🥯","🍞","🥖","🥨","🧀","🥚","🍳","🧈","🥞","🧇","🥓","🥩",
      "🍗","🍖","🌭","🍔","🍟","🍕","🥪","🌮","🌯","🫔","🥙","🧆","🥘","🍲","🥣",
      "🥗","🍿","🧂","🥫","🍱","🍘","🍙","🍚","🍛","🍜","🍝","🥧","🍣","🍤","🍥",
      "🥮","🍡","🥟","🥠","🥡","🍦","🍧","🍨","🍩","🍪","🎂","🍰","🧁","🍫","🍬",
      "🍭","🍮","🍯","🍼","🥛","☕️","🫖","🍵","🍶","🍾","🍷","🍸","🍹","🍺","🍻",
      "🥂","🥃","🥤","🧋","🧊"
    ]
  },

  {
    label: "⚽️",
    data: [
      "⚽️","🏀","🏈","⚾️","🥎","🎾","🏐","🎱","🏏","🏑","🏒","🏓","🏸","🥊","🥋",
      "⛳️","🎣","🤿","🏃","🎿","🛷","🎯","🪀","🪁","🎮","🕹","🎰","🎲","🧩","🧸",
      "🎨","🖼","🧵","🪡","🎸","🎹","🎺","🎻","🥁","🎤","🎧","🎟","🎭","🎖","🏆",
      "🥇","🥈","🥉"
    ]
  }
];

let globalEmojiId = 1000;
EMOJI_DATA.forEach(category => {
    category.data.forEach(emoji => {
        const id = `emoji-${globalEmojiId}`;
        const cleanEmoji = emoji.trim();
        if (!cleanEmoji || cleanEmoji.length > 8) return;

        BUSINESS_ICONS[id] = EmojiWrapper(cleanEmoji);

        const colorKeys = Object.keys(COLORS);
        const colorKey = colorKeys[globalEmojiId % colorKeys.length] as keyof typeof COLORS;

        LOGO_OPTIONS.push({
            id: globalEmojiId.toString(),
            icon: id,
            ...COLORS[colorKey],
            label: cleanEmoji
        });
        globalEmojiId++;
    });
});
